# Generated by Django 2.0.3 on 2020-07-19 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200306_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=256)),
                ('questtype', models.CharField(choices=[('radio ', 'Radio'), ('checkbox', 'Checkbox')], max_length=25)),
                ('answer', models.CharField(max_length=256)),
                ('scoreanswer', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('desciption', models.CharField(max_length=256)),
                ('quest_date', models.DateTimeField(default=datetime.datetime(2020, 7, 20, 0, 16, 42, 405709))),
            ],
        ),
        migrations.AlterField(
            model_name='personne',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 0, 16, 42, 402728)),
        ),
        migrations.AddField(
            model_name='questions',
            name='personne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.Personne'),
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.questions', unique=True),
        ),
    ]
